(load "~/.emacs.d/frame.el" nil t)
(load "~/.emacs.d/speedbar.el" nil t)
(load "~/.emacs.d/edit.el" nil t)
(load "~/.emacs.d/spell.el" nil t)
(load "~/.emacs.d/shell.el" nil t)
(load "~/.emacs.d/dired.el" nil t)
(load "~/.emacs.d/latex.el" nil t)
(load "~/.emacs.d/haskell.el" nil t)
(load "~/.emacs.d/md.el" nil t)
(load "~/.emacs.d/theme.el" nil t)

